<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['country_name' => 'Afghanistan', 'country_alpha_code' => 'AFG', 'country_phone_code' => '+93'],
            ['country_name' => 'Åland Islands', 'country_alpha_code' => 'ALA', 'country_phone_code' => '+358'],
            ['country_name' => 'Albania', 'country_alpha_code' => 'ALB', 'country_phone_code' => '+355'],
            ['country_name' => 'Algeria', 'country_alpha_code' => 'DZA', 'country_phone_code' => '+213'],
            ['country_name' => 'American Samoa', 'country_alpha_code' => 'ASM', 'country_phone_code' => '+1684'],
            ['country_name' => 'Andorra', 'country_alpha_code' => 'AND', 'country_phone_code' => '+376'],
            ['country_name' => 'Angola', 'country_alpha_code' => 'AGO', 'country_phone_code' => '+244'],
            ['country_name' => 'Anguilla', 'country_alpha_code' => 'AIA', 'country_phone_code' => '+1264'],
            ['country_name' => 'Antarctica', 'country_alpha_code' => 'ATA', 'country_phone_code' => '+672'],
            ['country_name' => 'Antigua and Barbuda', 'country_alpha_code' => 'ATG', 'country_phone_code' => '+1268'],
            ['country_name' => 'Argentina', 'country_alpha_code' => 'ARG', 'country_phone_code' => '+54'],
            ['country_name' => 'Armenia', 'country_alpha_code' => 'ARM', 'country_phone_code' => '+374'],
            ['country_name' => 'Aruba', 'country_alpha_code' => 'ABW', 'country_phone_code' => '+297'],
            ['country_name' => 'Australia', 'country_alpha_code' => 'AUS', 'country_phone_code' => '+61'],
            ['country_name' => 'Austria', 'country_alpha_code' => 'AUT', 'country_phone_code' => '+43'],
            ['country_name' => 'Azerbaijan', 'country_alpha_code' => 'AZE', 'country_phone_code' => '+994'],
            ['country_name' => 'Bahamas', 'country_alpha_code' => 'BHS', 'country_phone_code' => '+1242'],
            ['country_name' => 'Bahrain', 'country_alpha_code' => 'BHR', 'country_phone_code' => '+973'],
            ['country_name' => 'Bangladesh', 'country_alpha_code' => 'BGD', 'country_phone_code' => '+880'],
            ['country_name' => 'Barbados', 'country_alpha_code' => 'BRB', 'country_phone_code' => '+1246'],
            ['country_name' => 'Belarus', 'country_alpha_code' => 'BLR', 'country_phone_code' => '+375'],
            ['country_name' => 'Belgium', 'country_alpha_code' => 'BEL', 'country_phone_code' => '+32'],
            ['country_name' => 'Belize', 'country_alpha_code' => 'BLZ', 'country_phone_code' => '+501'],
            ['country_name' => 'Benin', 'country_alpha_code' => 'BEN', 'country_phone_code' => '+229'],
            ['country_name' => 'Bermuda', 'country_alpha_code' => 'BMU', 'country_phone_code' => '+1441'],
            ['country_name' => 'Bhutan', 'country_alpha_code' => 'BTN', 'country_phone_code' => '+975'],
            ['country_name' => 'Bolivia', 'country_alpha_code' => 'BOL', 'country_phone_code' => '+591'],
            ['country_name' => 'Bonaire, Sint Eustatius and Saba', 'country_alpha_code' => 'BES', 'country_phone_code' => '+599'],
            ['country_name' => 'Bosnia and Herzegovina', 'country_alpha_code' => 'BIH', 'country_phone_code' => '+387'],
            ['country_name' => 'Botswana', 'country_alpha_code' => 'BWA', 'country_phone_code' => '+267'],
            ['country_name' => 'Bouvet Island', 'country_alpha_code' => 'BVT', 'country_phone_code' => '+47'],
            ['country_name' => 'Brazil', 'country_alpha_code' => 'BRA', 'country_phone_code' => '+55'],
            ['country_name' => 'British Indian Ocean Territory', 'country_alpha_code' => 'IOT', 'country_phone_code' => '+246'],
            ['country_name' => 'Brunei Darussalam', 'country_alpha_code' => 'BRN', 'country_phone_code' => '+673'],
            ['country_name' => 'Bulgaria', 'country_alpha_code' => 'BGR', 'country_phone_code' => '+359'],
            ['country_name' => 'Burkina Faso', 'country_alpha_code' => 'BFA', 'country_phone_code' => '+226'],
            ['country_name' => 'Burundi', 'country_alpha_code' => 'BDI', 'country_phone_code' => '+257'],
            ['country_name' => 'Cabo Verde', 'country_alpha_code' => 'CPV', 'country_phone_code' => '+238'],
            ['country_name' => 'Cambodia', 'country_alpha_code' => 'KHM', 'country_phone_code' => '+855'],
            ['country_name' => 'Cameroon', 'country_alpha_code' => 'CMR', 'country_phone_code' => '+237'],
            ['country_name' => 'Canada', 'country_alpha_code' => 'CAN', 'country_phone_code' => '+1'],
            ['country_name' => 'Cayman Islands', 'country_alpha_code' => 'CYM', 'country_phone_code' => '+1345'],
            ['country_name' => 'Central African Republic', 'country_alpha_code' => 'CAF', 'country_phone_code' => '+236'],
            ['country_name' => 'Chad', 'country_alpha_code' => 'TCD', 'country_phone_code' => '+235'],
            ['country_name' => 'Chile', 'country_alpha_code' => 'CHL', 'country_phone_code' => '+56'],
            ['country_name' => 'China', 'country_alpha_code' => 'CHN', 'country_phone_code' => '+86'],
            ['country_name' => 'Christmas Island', 'country_alpha_code' => 'CXR', 'country_phone_code' => '+61'],
            ['country_name' => 'Cocos Islands', 'country_alpha_code' => 'CCK', 'country_phone_code' => '+61'],
            ['country_name' => 'Colombia', 'country_alpha_code' => 'COL', 'country_phone_code' => '+57'],
            ['country_name' => 'Comoros', 'country_alpha_code' => 'COM', 'country_phone_code' => '+269'],
            ['country_name' => 'Congo', 'country_alpha_code' => 'COG', 'country_phone_code' => '+242'],
            ['country_name' => 'Congo, Democratic Republic of the', 'country_alpha_code' => 'COD', 'country_phone_code' => '+243'],
            ['country_name' => 'Cook Islands', 'country_alpha_code' => 'COK', 'country_phone_code' => '+682'],
            ['country_name' => 'Costa Rica', 'country_alpha_code' => 'CRI', 'country_phone_code' => '+506'],
            ['country_name' => 'Côte d\'Ivoire', 'country_alpha_code' => 'CIV', 'country_phone_code' => '+225'],
            ['country_name' => 'Croatia', 'country_alpha_code' => 'HRV', 'country_phone_code' => '+385'],
            ['country_name' => 'Cuba', 'country_alpha_code' => 'CUB', 'country_phone_code' => '+53'],
            ['country_name' => 'Curaçao', 'country_alpha_code' => 'CUW', 'country_phone_code' => '+599'],
            ['country_name' => 'Cyprus', 'country_alpha_code' => 'CYP', 'country_phone_code' => '+357'],
            ['country_name' => 'Czechia', 'country_alpha_code' => 'CZE', 'country_phone_code' => '+420'],
            ['country_name' => 'Denmark', 'country_alpha_code' => 'DNK', 'country_phone_code' => '+45'],
            ['country_name' => 'Djibouti', 'country_alpha_code' => 'DJI', 'country_phone_code' => '+253'],
            ['country_name' => 'Dominica', 'country_alpha_code' => 'DMA', 'country_phone_code' => '+1767'],
            ['country_name' => 'Dominican Republic', 'country_alpha_code' => 'DOM', 'country_phone_code' => '+1'],
            ['country_name' => 'Ecuador', 'country_alpha_code' => 'ECU', 'country_phone_code' => '+593'],
            ['country_name' => 'Egypt', 'country_alpha_code' => 'EGY', 'country_phone_code' => '+20'],
            ['country_name' => 'El Salvador', 'country_alpha_code' => 'SLV', 'country_phone_code' => '+503'],
            ['country_name' => 'Equatorial Guinea', 'country_alpha_code' => 'GNQ', 'country_phone_code' => '+240'],
            ['country_name' => 'Eritrea', 'country_alpha_code' => 'ERI', 'country_phone_code' => '+291'],
            ['country_name' => 'Estonia', 'country_alpha_code' => 'EST', 'country_phone_code' => '+372'],
            ['country_name' => 'Eswatini', 'country_alpha_code' => 'SWZ', 'country_phone_code' => '+268'],
            ['country_name' => 'Ethiopia', 'country_alpha_code' => 'ETH', 'country_phone_code' => '+251'],
            ['country_name' => 'Falkland Islands', 'country_alpha_code' => 'FLK', 'country_phone_code' => '+500'],
            ['country_name' => 'Faroe Islands', 'country_alpha_code' => 'FRO', 'country_phone_code' => '+298'],
            ['country_name' => 'Fiji', 'country_alpha_code' => 'FJI', 'country_phone_code' => '+679'],
            ['country_name' => 'Finland', 'country_alpha_code' => 'FIN', 'country_phone_code' => '+358'],
            ['country_name' => 'France', 'country_alpha_code' => 'FRA', 'country_phone_code' => '+33'],
            ['country_name' => 'French Guiana', 'country_alpha_code' => 'GUF', 'country_phone_code' => '+594'],
            ['country_name' => 'French Polynesia', 'country_alpha_code' => 'PYF', 'country_phone_code' => '+689'],
            ['country_name' => 'French Southern Territories', 'country_alpha_code' => 'ATF', 'country_phone_code' => '+262'],
            ['country_name' => 'Gabon', 'country_alpha_code' => 'GAB', 'country_phone_code' => '+241'],
            ['country_name' => 'Gambia', 'country_alpha_code' => 'GMB', 'country_phone_code' => '+220'],
            ['country_name' => 'Georgia', 'country_alpha_code' => 'GEO', 'country_phone_code' => '+995'],
            ['country_name' => 'Germany', 'country_alpha_code' => 'DEU', 'country_phone_code' => '+49'],
            ['country_name' => 'Ghana', 'country_alpha_code' => 'GHA', 'country_phone_code' => '+233'],
            ['country_name' => 'Gibraltar', 'country_alpha_code' => 'GIB', 'country_phone_code' => '+350'],
            ['country_name' => 'Greece', 'country_alpha_code' => 'GRC', 'country_phone_code' => '+30'],
            ['country_name' => 'Greenland', 'country_alpha_code' => 'GRL', 'country_phone_code' => '+299'],
            ['country_name' => 'Grenada', 'country_alpha_code' => 'GRD', 'country_phone_code' => '+1473'],
            ['country_name' => 'Guadeloupe', 'country_alpha_code' => 'GLP', 'country_phone_code' => '+590'],
            ['country_name' => 'Guam', 'country_alpha_code' => 'GUM', 'country_phone_code' => '+1671'],
            ['country_name' => 'Guatemala', 'country_alpha_code' => 'GTM', 'country_phone_code' => '+502'],
            ['country_name' => 'Guernsey', 'country_alpha_code' => 'GGY', 'country_phone_code' => '+44'],
            ['country_name' => 'Guinea', 'country_alpha_code' => 'GIN', 'country_phone_code' => '+224'],
            ['country_name' => 'Guinea-Bissau', 'country_alpha_code' => 'GNB', 'country_phone_code' => '+245'],
            ['country_name' => 'Guyana', 'country_alpha_code' => 'GUY', 'country_phone_code' => '+592'],
            ['country_name' => 'Haiti', 'country_alpha_code' => 'HTI', 'country_phone_code' => '+509'],
            ['country_name' => 'Heard Island and McDonald Islands', 'country_alpha_code' => 'HMD', 'country_phone_code' => '+672'],
            ['country_name' => 'Holy See', 'country_alpha_code' => 'VAT', 'country_phone_code' => '+39'],
            ['country_name' => 'Honduras', 'country_alpha_code' => 'HND', 'country_phone_code' => '+504'],
            ['country_name' => 'Hong Kong', 'country_alpha_code' => 'HKG', 'country_phone_code' => '+852'],
            ['country_name' => 'Hungary', 'country_alpha_code' => 'HUN', 'country_phone_code' => '+36'],
            ['country_name' => 'Iceland', 'country_alpha_code' => 'ISL', 'country_phone_code' => '+354'],
            ['country_name' => 'India', 'country_alpha_code' => 'IND', 'country_phone_code' => '+91'],
            ['country_name' => 'Indonesia', 'country_alpha_code' => 'IDN', 'country_phone_code' => '+62'],
            ['country_name' => 'Iran', 'country_alpha_code' => 'IRN', 'country_phone_code' => '+98'],
            ['country_name' => 'Iraq', 'country_alpha_code' => 'IRQ', 'country_phone_code' => '+964'],
            ['country_name' => 'Ireland', 'country_alpha_code' => 'IRL', 'country_phone_code' => '+353'],
            ['country_name' => 'Isle of Man', 'country_alpha_code' => 'IMN', 'country_phone_code' => '+44'],
            ['country_name' => 'Israel', 'country_alpha_code' => 'ISR', 'country_phone_code' => '+972'],
            ['country_name' => 'Italy', 'country_alpha_code' => 'ITA', 'country_phone_code' => '+39'],
            ['country_name' => 'Jamaica', 'country_alpha_code' => 'JAM', 'country_phone_code' => '+1876'],
            ['country_name' => 'Japan', 'country_alpha_code' => 'JPN', 'country_phone_code' => '+81'],
            ['country_name' => 'Jersey', 'country_alpha_code' => 'JEY', 'country_phone_code' => '+44'],
            ['country_name' => 'Jordan', 'country_alpha_code' => 'JOR', 'country_phone_code' => '+962'],
            ['country_name' => 'Kazakhstan', 'country_alpha_code' => 'KAZ', 'country_phone_code' => '+7'],
            ['country_name' => 'Kenya', 'country_alpha_code' => 'KEN', 'country_phone_code' => '+254'],
            ['country_name' => 'Kiribati', 'country_alpha_code' => 'KIR', 'country_phone_code' => '+686'],
            ['country_name' => 'Korea, Democratic People\'s Republic of', 'country_alpha_code' => 'PRK', 'country_phone_code' => '+850'],
            ['country_name' => 'Korea, Republic of', 'country_alpha_code' => 'KOR', 'country_phone_code' => '+82'],
            ['country_name' => 'Kuwait', 'country_alpha_code' => 'KWT', 'country_phone_code' => '+965'],
            ['country_name' => 'Kyrgyzstan', 'country_alpha_code' => 'KGZ', 'country_phone_code' => '+996'],
            ['country_name' => 'Lao People\'s Democratic Republic', 'country_alpha_code' => 'LAO', 'country_phone_code' => '+856'],
            ['country_name' => 'Latvia', 'country_alpha_code' => 'LVA', 'country_phone_code' => '+371'],
            ['country_name' => 'Lebanon', 'country_alpha_code' => 'LBN', 'country_phone_code' => '+961'],
            ['country_name' => 'Lesotho', 'country_alpha_code' => 'LSO', 'country_phone_code' => '+266'],
            ['country_name' => 'Liberia', 'country_alpha_code' => 'LBR', 'country_phone_code' => '+231'],
            ['country_name' => 'Libya', 'country_alpha_code' => 'LBY', 'country_phone_code' => '+218'],
            ['country_name' => 'Liechtenstein', 'country_alpha_code' => 'LIE', 'country_phone_code' => '+423'],
            ['country_name' => 'Lithuania', 'country_alpha_code' => 'LTU', 'country_phone_code' => '+370'],
            ['country_name' => 'Luxembourg', 'country_alpha_code' => 'LUX', 'country_phone_code' => '+352'],
            ['country_name' => 'Macao', 'country_alpha_code' => 'MAC', 'country_phone_code' => '+853'],
            ['country_name' => 'Madagascar', 'country_alpha_code' => 'MDG', 'country_phone_code' => '+261'],
            ['country_name' => 'Malawi', 'country_alpha_code' => 'MWI', 'country_phone_code' => '+265'],
            ['country_name' => 'Malaysia', 'country_alpha_code' => 'MYS', 'country_phone_code' => '+60'],
            ['country_name' => 'Maldives', 'country_alpha_code' => 'MDV', 'country_phone_code' => '+960'],
            ['country_name' => 'Mali', 'country_alpha_code' => 'MLI', 'country_phone_code' => '+223'],
            ['country_name' => 'Malta', 'country_alpha_code' => 'MLT', 'country_phone_code' => '+356'],
            ['country_name' => 'Marshall Islands', 'country_alpha_code' => 'MHL', 'country_phone_code' => '+692'],
            ['country_name' => 'Martinique', 'country_alpha_code' => 'MTQ', 'country_phone_code' => '+596'],
            ['country_name' => 'Mauritania', 'country_alpha_code' => 'MRT', 'country_phone_code' => '+222'],
            ['country_name' => 'Mauritius', 'country_alpha_code' => 'MUS', 'country_phone_code' => '+230'],
            ['country_name' => 'Mayotte', 'country_alpha_code' => 'MYT', 'country_phone_code' => '+262'],
            ['country_name' => 'Mexico', 'country_alpha_code' => 'MEX', 'country_phone_code' => '+52'],
            ['country_name' => 'Micronesia', 'country_alpha_code' => 'FSM', 'country_phone_code' => '+691'],
            ['country_name' => 'Moldova', 'country_alpha_code' => 'MDA', 'country_phone_code' => '+373'],
            ['country_name' => 'Monaco', 'country_alpha_code' => 'MCO', 'country_phone_code' => '+377'],
            ['country_name' => 'Mongolia', 'country_alpha_code' => 'MNG', 'country_phone_code' => '+976'],
            ['country_name' => 'Montenegro', 'country_alpha_code' => 'MNE', 'country_phone_code' => '+382'],
            ['country_name' => 'Montserrat', 'country_alpha_code' => 'MSR', 'country_phone_code' => '+1664'],
            ['country_name' => 'Morocco', 'country_alpha_code' => 'MAR', 'country_phone_code' => '+212'],
            ['country_name' => 'Mozambique', 'country_alpha_code' => 'MOZ', 'country_phone_code' => '+258'],
            ['country_name' => 'Myanmar', 'country_alpha_code' => 'MMR', 'country_phone_code' => '+95'],
            ['country_name' => 'Namibia', 'country_alpha_code' => 'NAM', 'country_phone_code' => '+264'],
            ['country_name' => 'Nauru', 'country_alpha_code' => 'NRU', 'country_phone_code' => '+674'],
            ['country_name' => 'Nepal', 'country_alpha_code' => 'NPL', 'country_phone_code' => '+977'],
            ['country_name' => 'Netherlands', 'country_alpha_code' => 'NLD', 'country_phone_code' => '+31'],
            ['country_name' => 'New Caledonia', 'country_alpha_code' => 'NCL', 'country_phone_code' => '+687'],
            ['country_name' => 'New Zealand', 'country_alpha_code' => 'NZL', 'country_phone_code' => '+64'],
            ['country_name' => 'Nicaragua', 'country_alpha_code' => 'NIC', 'country_phone_code' => '+505'],
            ['country_name' => 'Niger', 'country_alpha_code' => 'NER', 'country_phone_code' => '+227'],
            ['country_name' => 'Nigeria', 'country_alpha_code' => 'NGA', 'country_phone_code' => '+234'],
            ['country_name' => 'Niue', 'country_alpha_code' => 'NIU', 'country_phone_code' => '+683'],
            ['country_name' => 'Norfolk Island', 'country_alpha_code' => 'NFK', 'country_phone_code' => '+672'],
            ['country_name' => 'North Macedonia', 'country_alpha_code' => 'MKD', 'country_phone_code' => '+389'],
            ['country_name' => 'Northern Mariana Islands', 'country_alpha_code' => 'MNP', 'country_phone_code' => '+1670'],
            ['country_name' => 'Norway', 'country_alpha_code' => 'NOR', 'country_phone_code' => '+47'],
            ['country_name' => 'Oman', 'country_alpha_code' => 'OMN', 'country_phone_code' => '+968'],
            ['country_name' => 'Pakistan', 'country_alpha_code' => 'PAK', 'country_phone_code' => '+92'],
            ['country_name' => 'Palau', 'country_alpha_code' => 'PLW', 'country_phone_code' => '+680'],
            ['country_name' => 'Palestine, State of', 'country_alpha_code' => 'PSE', 'country_phone_code' => '+970'],
            ['country_name' => 'Panama', 'country_alpha_code' => 'PAN', 'country_phone_code' => '+507'],
            ['country_name' => 'Papua New Guinea', 'country_alpha_code' => 'PNG', 'country_phone_code' => '+675'],
            ['country_name' => 'Paraguay', 'country_alpha_code' => 'PRY', 'country_phone_code' => '+595'],
            ['country_name' => 'Peru', 'country_alpha_code' => 'PER', 'country_phone_code' => '+51'],
            ['country_name' => 'Philippines', 'country_alpha_code' => 'PHL', 'country_phone_code' => '+63'],
            ['country_name' => 'Pitcairn', 'country_alpha_code' => 'PCN', 'country_phone_code' => '+64'],
            ['country_name' => 'Poland', 'country_alpha_code' => 'POL', 'country_phone_code' => '+48'],
            ['country_name' => 'Portugal', 'country_alpha_code' => 'PRT', 'country_phone_code' => '+351'],
            ['country_name' => 'Puerto Rico', 'country_alpha_code' => 'PRI', 'country_phone_code' => '+1'],
            ['country_name' => 'Qatar', 'country_alpha_code' => 'QAT', 'country_phone_code' => '+974'],
            ['country_name' => 'Réunion', 'country_alpha_code' => 'REU', 'country_phone_code' => '+262'],
            ['country_name' => 'Romania', 'country_alpha_code' => 'ROU', 'country_phone_code' => '+40'],
            ['country_name' => 'Russian Federation', 'country_alpha_code' => 'RUS', 'country_phone_code' => '+7'],
            ['country_name' => 'Rwanda', 'country_alpha_code' => 'RWA', 'country_phone_code' => '+250'],
            ['country_name' => 'Saint Barthélemy', 'country_alpha_code' => 'BLM', 'country_phone_code' => '+590'],
            ['country_name' => 'Saint Helena, Ascension and Tristan da Cunha', 'country_alpha_code' => 'SHN', 'country_phone_code' => '+290'],
            ['country_name' => 'Saint Kitts and Nevis', 'country_alpha_code' => 'KNA', 'country_phone_code' => '+1869'],
            ['country_name' => 'Saint Lucia', 'country_alpha_code' => 'LCA', 'country_phone_code' => '+1758'],
            ['country_name' => 'Saint Martin (French part)', 'country_alpha_code' => 'MAF', 'country_phone_code' => '+590'],
            ['country_name' => 'Saint Pierre and Miquelon', 'country_alpha_code' => 'SPM', 'country_phone_code' => '+508'],
            ['country_name' => 'Saint Vincent and the Grenadines', 'country_alpha_code' => 'VCT', 'country_phone_code' => '+1784'],
            ['country_name' => 'Samoa', 'country_alpha_code' => 'WSM', 'country_phone_code' => '+685'],
            ['country_name' => 'San Marino', 'country_alpha_code' => 'SMR', 'country_phone_code' => '+378'],
            ['country_name' => 'Sao Tome and Principe', 'country_alpha_code' => 'STP', 'country_phone_code' => '+239'],
            ['country_name' => 'Saudi Arabia', 'country_alpha_code' => 'SAU', 'country_phone_code' => '+966'],
            ['country_name' => 'Senegal', 'country_alpha_code' => 'SEN', 'country_phone_code' => '+221'],
            ['country_name' => 'Serbia', 'country_alpha_code' => 'SRB', 'country_phone_code' => '+381'],
            ['country_name' => 'Seychelles', 'country_alpha_code' => 'SYC', 'country_phone_code' => '+248'],
            ['country_name' => 'Sierra Leone', 'country_alpha_code' => 'SLE', 'country_phone_code' => '+232'],
            ['country_name' => 'Singapore', 'country_alpha_code' => 'SGP', 'country_phone_code' => '+65'],
            ['country_name' => 'Sint Maarten (Dutch part)', 'country_alpha_code' => 'SXM', 'country_phone_code' => '+1721'],
            ['country_name' => 'Slovakia', 'country_alpha_code' => 'SVK', 'country_phone_code' => '+421'],
            ['country_name' => 'Slovenia', 'country_alpha_code' => 'SVN', 'country_phone_code' => '+386'],
            ['country_name' => 'Solomon Islands', 'country_alpha_code' => 'SLB', 'country_phone_code' => '+677'],
            ['country_name' => 'Somalia', 'country_alpha_code' => 'SOM', 'country_phone_code' => '+252'],
            ['country_name' => 'South Africa', 'country_alpha_code' => 'ZAF', 'country_phone_code' => '+27'],
            ['country_name' => 'South Georgia and the South Sandwich Islands', 'country_alpha_code' => 'SGS', 'country_phone_code' => '+500'],
            ['country_name' => 'South Sudan', 'country_alpha_code' => 'SSD', 'country_phone_code' => '+211'],
            ['country_name' => 'Spain', 'country_alpha_code' => 'ESP', 'country_phone_code' => '+34'],
            ['country_name' => 'Sri Lanka', 'country_alpha_code' => 'LKA', 'country_phone_code' => '+94'],
            ['country_name' => 'Sudan', 'country_alpha_code' => 'SDN', 'country_phone_code' => '+249'],
            ['country_name' => 'Suriname', 'country_alpha_code' => 'SUR', 'country_phone_code' => '+597'],
            ['country_name' => 'Svalbard and Jan Mayen', 'country_alpha_code' => 'SJM', 'country_phone_code' => '+47'],
            ['country_name' => 'Sweden', 'country_alpha_code' => 'SWE', 'country_phone_code' => '+46'],
            ['country_name' => 'Switzerland', 'country_alpha_code' => 'CHE', 'country_phone_code' => '+41'],
            ['country_name' => 'Syrian Arab Republic', 'country_alpha_code' => 'SYR', 'country_phone_code' => '+963'],
            ['country_name' => 'Taiwan, Province of China', 'country_alpha_code' => 'TWN', 'country_phone_code' => '+886'],
            ['country_name' => 'Tajikistan', 'country_alpha_code' => 'TJK', 'country_phone_code' => '+992'],
            ['country_name' => 'Tanzania, United Republic of', 'country_alpha_code' => 'TZA', 'country_phone_code' => '+255'],
            ['country_name' => 'Thailand', 'country_alpha_code' => 'THA', 'country_phone_code' => '+66'],
            ['country_name' => 'Timor-Leste', 'country_alpha_code' => 'TLS', 'country_phone_code' => '+670'],
            ['country_name' => 'Togo', 'country_alpha_code' => 'TGO', 'country_phone_code' => '+228'],
            ['country_name' => 'Tokelau', 'country_alpha_code' => 'TKL', 'country_phone_code' => '+690'],
            ['country_name' => 'Tonga', 'country_alpha_code' => 'TON', 'country_phone_code' => '+676'],
            ['country_name' => 'Trinidad and Tobago', 'country_alpha_code' => 'TTO', 'country_phone_code' => '+1868'],
            ['country_name' => 'Tunisia', 'country_alpha_code' => 'TUN', 'country_phone_code' => '+216'],
            ['country_name' => 'Turkey', 'country_alpha_code' => 'TUR', 'country_phone_code' => '+90'],
            ['country_name' => 'Turkmenistan', 'country_alpha_code' => 'TKM', 'country_phone_code' => '+993'],
            ['country_name' => 'Turks and Caicos Islands', 'country_alpha_code' => 'TCA', 'country_phone_code' => '+1649'],
            ['country_name' => 'Tuvalu', 'country_alpha_code' => 'TUV', 'country_phone_code' => '+688'],
            ['country_name' => 'Uganda', 'country_alpha_code' => 'UGA', 'country_phone_code' => '+256'],
            ['country_name' => 'Ukraine', 'country_alpha_code' => 'UKR', 'country_phone_code' => '+380'],
            ['country_name' => 'United Arab Emirates', 'country_alpha_code' => 'ARE', 'country_phone_code' => '+971'],
            ['country_name' => 'United Kingdom of Great Britain and Northern Ireland', 'country_alpha_code' => 'GBR', 'country_phone_code' => '+44'],
            ['country_name' => 'United States of America', 'country_alpha_code' => 'USA', 'country_phone_code' => '+1'],
            ['country_name' => 'United States Minor Outlying Islands', 'country_alpha_code' => 'UMI', 'country_phone_code' => '+1'],
            ['country_name' => 'Uruguay', 'country_alpha_code' => 'URY', 'country_phone_code' => '+598'],
            ['country_name' => 'Uzbekistan', 'country_alpha_code' => 'UZB', 'country_phone_code' => '+998'],
            ['country_name' => 'Vanuatu', 'country_alpha_code' => 'VUT', 'country_phone_code' => '+678'],
            ['country_name' => 'Venezuela', 'country_alpha_code' => 'VEN', 'country_phone_code' => '+58'],
            ['country_name' => 'Viet Nam', 'country_alpha_code' => 'VNM', 'country_phone_code' => '+84'],
            ['country_name' => 'Virgin Islands (British)', 'country_alpha_code' => 'VGB', 'country_phone_code' => '+1284'],
            ['country_name' => 'Virgin Islands (U.S.)', 'country_alpha_code' => 'VIR', 'country_phone_code' => '+1340'],
            ['country_name' => 'Wallis and Futuna', 'country_alpha_code' => 'WLF', 'country_phone_code' => '+681'],
            ['country_name' => 'Western Sahara', 'country_alpha_code' => 'ESH', 'country_phone_code' => '+212'],
            ['country_name' => 'Yemen', 'country_alpha_code' => 'YEM', 'country_phone_code' => '+967'],
            ['country_name' => 'Zambia', 'country_alpha_code' => 'ZMB', 'country_phone_code' => '+260'],
            ['country_name' => 'Zimbabwe', 'country_alpha_code' => 'ZWE', 'country_phone_code' => '+263'],
        ];

        // Clear existing data to avoid duplicates (optional)
        DB::table('countries')->truncate();

        // Insert all countries
        DB::table('countries')->insert($countries);
    }
}